name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'  # Use the latest stable version of Go

      - name: Update dependencies
        run: |
          cd backend
          go get -u ./...
          go mod tidy

      - name: Build application
        run: |
          cd backend
          go build -o CardVault
          cd ..
          zip -r application.zip backend/CardVault

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp application.zip s3://${{ secrets.AWS_EB_APPLICATION_NAME }}-deployment-bucket/application-${{ github.run_number }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name "${{ secrets.AWS_EB_APPLICATION_NAME }}" \
            --version-label "${{ github.run_number }}" --source-bundle S3Bucket="${{ secrets.AWS_EB_APPLICATION_NAME }}-deployment-bucket",S3Key="application-${{ github.run_number }}.zip"

          aws elasticbeanstalk update-environment --application-name "${{ secrets.AWS_EB_APPLICATION_NAME }}" \
            --environment-name "${{ secrets.AWS_EB_ENVIRONMENT_NAME }}" --version-label "${{ github.run_number }}"
